from colorama import Fore, Style

print("Hello World")
print(Fore.LIGHTBLACK_EX + "Hello World    серый")
print(Fore.BLACK + "Hello World    черный")
print(Fore.LIGHTBLUE_EX + "Hello World    светло-синий")
print(Fore.BLUE + "Hello World    синий")
print(Fore.LIGHTCYAN_EX + "Hello World    светло-голубой")
print(Fore.CYAN + "Hello World    \"морская волна\"")
print(Fore.LIGHTGREEN_EX + "Hello World    светло-зелёный")
print(Fore.GREEN + "Hello World    зелёный")
print(Fore.LIGHTMAGENTA_EX + "Hello World    светло-розовый")
print(Fore.MAGENTA + "Hello World    манжета")
print(Fore.LIGHTRED_EX + "Hello World    светло-крвсный")
print(Fore.RED + "Hello World    красный")
print(Fore.LIGHTWHITE_EX + "Hello World    ярко-белый")
print(Fore.WHITE + "Hello World    белый")
print(Fore.RESET + "Hello World    сброс цвета")
print(Fore.LIGHTYELLOW_EX + "Hello World    светло-желтый")
print(Fore.YELLOW + "Hello World    желтый")
print(Fore.RESET)
print(Style.BRIGHT + "Hello World")
